-- ====================================================================
-- MOAI ERP Database Schema - PostgreSQL (Supabase Compatible)
-- ====================================================================
-- Instructions for Supabase:
-- 1. Go to your Supabase Project Dashboard.
-- 2. Open the "SQL Editor" from the sidebar.
-- 3. Click "New Query" and paste the contents of this file.
-- 4. Click "Run" to create tables and seed initial data.
-- ====================================================================

-- 0. Drop tables if they exist to allow clean reinstall
DROP TABLE IF EXISTS calloffs;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;

-- 1. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Orders Table (Order Preparation)
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id VARCHAR(255) NOT NULL,
    boq_details TEXT NOT NULL,
    vc VARCHAR(255) NOT NULL,
    wbs VARCHAR(255) DEFAULT 'Missing' NOT NULL,
    status VARCHAR(255) NOT NULL, -- e.g., 'Pending', 'Clarified'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Shipments Table (Customs Process)
CREATE TABLE shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    awb VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL, -- e.g., 'In Transit', 'Customs Submitted'
    hs_code VARCHAR(255) NOT NULL,
    eta VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Inventory Table (Project WH GR/GI)
CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL, -- 'INBOUND' or 'OUTBOUND'
    items_count INTEGER NOT NULL CHECK (items_count > 0),
    status VARCHAR(255) NOT NULL, -- e.g., 'PENDING_GR', 'GR_COMPLETED', 'PENDING_GI', 'GI_COMPLETED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Call-offs Table (Material Call-off)
CREATE TABLE calloffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr VARCHAR(255) NOT NULL,
    site VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL, -- 'READY', 'ON_DELIVERY', 'POD_WAITING', 'COMPLETED'
    dsp VARCHAR(255) DEFAULT 'Unassigned' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Disable Row Level Security (RLS) for testing/prototype CRUD via Client SDK
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE shipments DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE calloffs DISABLE ROW LEVEL SECURITY;

-- Explicitly grant permissions to anon and authenticated roles
GRANT ALL ON users TO anon, authenticated;
GRANT ALL ON orders TO anon, authenticated;
GRANT ALL ON shipments TO anon, authenticated;
GRANT ALL ON inventory TO anon, authenticated;
GRANT ALL ON calloffs TO anon, authenticated;

-- ====================================================================
-- SEED DATA
-- ====================================================================

-- Seed initial admin user
INSERT INTO users (username, password, name, role) 
VALUES ('admin', 'password', 'Admin Utama', 'Supply Manager')
ON CONFLICT (username) DO NOTHING;

-- Seed initial orders
INSERT INTO orders (site_id, boq_details, vc, wbs, status) VALUES 
('ORD-2026-901 / JKT-NORTH-01', 'Baseband Unit v2', 'VC-440-992', 'NRO-CAPEX-26', 'Clarified'),
('ORD-2026-902 / SBY-EAST-11', 'Radio Antenna 5G', 'VC-440-881', 'Missing', 'Pending');

-- Seed initial shipments
INSERT INTO shipments (awb, description, status, hs_code, eta) VALUES 
('998-2342-111', 'Shipment from Hub (EAB)', 'In Transit', '8517.62.00', '12 Jul 2026');

-- Seed initial inventory transactions
INSERT INTO inventory (reference, type, items_count, status) VALUES 
('PO: 450092110', 'INBOUND', 12, 'PENDING_GR'),
('MR: REQ-9920', 'OUTBOUND', 5, 'PENDING_GI');

-- Seed initial call-off dispatches
INSERT INTO calloffs (mr, site, status, dsp) VALUES 
('MR: 9920-A', 'BDO-CEN-05', 'READY', 'Unassigned'),
('MR: 9811-B', 'JKT-SOU-12', 'ON_DELIVERY', 'Mitra Logistik PT'),
('MR: 9102-C', 'SBY-WES-01', 'POD_WAITING', 'Lintas Express');
